name: form_forge_generator
description: >-
  Code generator for form_forge. Processes @FormForge() annotations and
  generates FormController and FormWidget classes.
version: 0.1.0
publish_to: none # Uses path deps during development; updated for publish
homepage: https://github.com/sahilsharma/form_forge
repository: https://github.com/sahilsharma/form_forge

environment:
  sdk: ^3.6.2

dependencies:
  form_forge:
    path: ../form_forge
  source_gen: ^2.0.0
  analyzer: '>=6.0.0 <7.0.0'
  build: ^2.4.0

dev_dependencies:
  build_runner: '>=2.4.0 <2.5.0'
  build_test: ^2.2.2
  test: ^1.25.0
  flutter_lints: ^5.0.0

resolution: workspace
